- name: vim config
  file:
    owner: ubuntu
    path: /home/vagrant/.vimrc
    mode: 0644
    state: touch
- name: inputrc
  lineinfile:
    owner: ubuntu
    path: /home/vagrant/.inputrc
    line: 'set editing-mode vi'
    create: yes
- name: vim directories
  file:
    owner: ubuntu
    path: "/home/vagrant/.vim/{{item}}"
    state: directory
    mode: 0755
  with_items:
    - bundle
    - autoload
- name: cmake required for YouCompleteMe
  apt: name=cmake update_cache=yes
- name: install vundle
  git:
    repo: https://github.com/gmarik/Vundle.vim.git
    dest: /home/vagrant/.vim/bundle/Vundle.vim
- name: extra vim config
  blockinfile:
    path: /home/vagrant/.vimrc
    marker: "\" {mark} from playbook"
    block:  "{{ lookup('file', 'vimrc') }}"
